import { SOURCE_URLS } from "./constants";

export type DataSourceRecord = {
  id: string;
  dataset: string;
  provider: string;
  sourceUrl: string;
  purpose: string;
  dataType: string;
  resolution: string;
  lastImported: string;
  license: string;
  classification: "official" | "open-data" | "modelled" | "derived";
  limitations: string;
  usedInScoring: boolean;
  refresh: string;
};

export const DATA_SOURCES: DataSourceRecord[] = [
  {
    id: "osm",
    dataset: "Locality boundaries, buildings, roads, places, land use and waterways",
    provider: "OpenStreetMap contributors",
    sourceUrl: SOURCE_URLS.osm,
    purpose: "Local 3D geometry, search, amenities, transport, water and land-use features per locality",
    dataType: "Open collaborative geodata",
    resolution: "Individual mapped objects; completeness varies by locality",
    lastImported: "Generated with npm run data:ingest --locality <id>",
    license: "ODbL 1.0 — attribution and share-alike obligations apply",
    classification: "open-data",
    limitations: "Crowdsourced mapping can be incomplete or stale. Unmapped objects are not assumed absent.",
    usedInScoring: true,
    refresh: "Manual versioned ingestion per locality",
  },
  {
    id: "boundary",
    dataset: "Locality boundary polygons — OSM admin boundary relations",
    provider: "OpenStreetMap; relation source tags reference Bengaluru Development Authority and BBMP",
    sourceUrl: "https://www.openstreetmap.org/",
    purpose: "Scope boundary and clipping mask per locality",
    dataType: "Locality boundary polygon",
    resolution: "Mapped polygon per locality",
    lastImported: "Generated with npm run data:ingest --locality <id>",
    license: "ODbL 1.0",
    classification: "open-data",
    limitations: "A locality boundary may not exactly match the corresponding municipal ward boundary.",
    usedInScoring: false,
    refresh: "Manual versioned ingestion",
  },
  {
    id: "weather",
    dataset: "Weather forecast and recent model context",
    provider: "Open-Meteo",
    sourceUrl: SOURCE_URLS.openMeteo,
    purpose: "Observed-model and forecast rainfall context",
    dataType: "Modelled",
    resolution: "Provider-selected weather-model grid; not a 100 m observation",
    lastImported: "Fetched server-side on demand",
    license: "CC BY 4.0; Open-Meteo attribution required",
    classification: "modelled",
    limitations: "Forecast-grid values do not represent conditions at a particular street or property.",
    usedInScoring: true,
    refresh: "15-minute server cache",
  },
  {
    id: "air",
    dataset: "CAMS global atmospheric composition forecast via Open-Meteo",
    provider: "Open-Meteo / Copernicus Atmosphere Monitoring Service",
    sourceUrl: SOURCE_URLS.openMeteoAir,
    purpose: "Outdoor PM2.5 and regional AQI context",
    dataType: "Modelled",
    resolution: "Approximately 45 km in the global CAMS model used for Bengaluru",
    lastImported: "Fetched server-side on demand",
    license: "CC BY 4.0 data attribution",
    classification: "modelled",
    limitations: "Regional model output is not indoor, street-level, or building-level air monitoring.",
    usedInScoring: true,
    refresh: "45-minute server cache",
  },
  {
    id: "drains",
    dataset: "Bengaluru Stormwater Drains Maps 2022",
    provider: "BBMP, published by OpenCity",
    sourceUrl: SOURCE_URLS.openCityDrains,
    purpose: "Mapped stormwater-drain proximity and flood context",
    dataType: "Imported KML line geometry",
    resolution: "Primary, secondary and tertiary mapped drains; coverage varies by locality",
    lastImported: "Generated with npm run data:ingest --locality <id>",
    license: "Dataset page terms; provider attribution retained",
    classification: "open-data",
    limitations: "Map publication does not guarantee present condition, capacity, maintenance, or completeness. Some localities have sparse coverage.",
    usedInScoring: true,
    refresh: "Versioned static import",
  },
  {
    id: "flood",
    dataset: "Flood-vulnerable, flood-prone, and BBMP low-lying locations",
    provider: "Government and BBMP-derived layers published by OpenCity",
    sourceUrl: SOURCE_URLS.openCityFlood,
    purpose: "Historical/documented susceptibility context per locality",
    dataType: "Imported KML point geometry",
    resolution: "Mapped locations with varying source dates; coverage varies by locality",
    lastImported: "Generated with npm run data:ingest --locality <id>",
    license: "OpenCity package marks the dataset Public Domain / other",
    classification: "open-data",
    limitations: "Known locations are not a complete inventory. Proximity does not predict that a cell will flood. Sparse coverage in some localities is shown explicitly.",
    usedInScoring: true,
    refresh: "Versioned static import",
  },
  {
    id: "elevation",
    dataset: "Copernicus DEM GLO-90 elevation",
    provider: "Copernicus Programme via Open-Meteo Elevation API",
    sourceUrl: "https://open-meteo.com/en/docs/elevation-api",
    purpose: "Cell-centre elevation, relative elevation and local-slope flood features",
    dataType: "Digital elevation model",
    resolution: "90 m source grid sampled at each 100 m cell centre",
    lastImported: "Generated with npm run data:ingest --locality <id>",
    license: "Copernicus data attribution plus Open-Meteo attribution",
    classification: "modelled",
    limitations: "Cannot resolve basements, kerbs, building pads, local drain condition, or sub-cell depressions.",
    usedInScoring: true,
    refresh: "Static versioned import",
  },
  {
    id: "noise",
    dataset: "Environmental-noise proxy",
    provider: "UrbanLens derived metric",
    sourceUrl: "/methodology#noise",
    purpose: "Low-confidence road and activity exposure estimate",
    dataType: "Derived",
    resolution: "100 m analysis cell",
    lastImported: "Recalculated during ingestion",
    license: "Methodology published in this application",
    classification: "derived",
    limitations: "Not a sound-pressure measurement; traffic volume, barriers, floor height and time of day are absent.",
    usedInScoring: true,
    refresh: "Whenever OSM source geometry is re-ingested",
  },
  {
    id: "education",
    dataset: "Schools, colleges and kindergartens",
    provider: "OpenStreetMap contributors",
    sourceUrl: SOURCE_URLS.osm,
    purpose: "Proximity + density access proxy for education",
    dataType: "Open collaborative geodata (points)",
    resolution: "100 m cell; nearest-feature distance and 600 m density",
    lastImported: "Generated with npm run data:ingest --locality <id>",
    license: "ODbL 1.0",
    classification: "derived",
    limitations: "Access proxy only; not a quality rating of any institution. UDISE+ is district/block-level and not used for street-resolution scoring.",
    usedInScoring: true,
    refresh: "Versioned OSM ingestion",
  },
  {
    id: "healthcare",
    dataset: "Hospitals, clinics, doctors and pharmacies",
    provider: "OpenStreetMap contributors",
    sourceUrl: SOURCE_URLS.osm,
    purpose: "Proximity + density access proxy for healthcare",
    dataType: "Open collaborative geodata (points)",
    resolution: "100 m cell; nearest-feature distance and 600 m density",
    lastImported: "Generated with npm run data:ingest --locality <id>",
    license: "ODbL 1.0",
    classification: "derived",
    limitations: "Does not describe capacity, quality, specialisation, or opening hours.",
    usedInScoring: true,
    refresh: "Versioned OSM ingestion",
  },
  {
    id: "transit",
    dataset: "Bus stops and Namma Metro stations",
    provider: "OpenStreetMap contributors",
    sourceUrl: SOURCE_URLS.osm,
    purpose: "Public-transport access proxy",
    dataType: "Open collaborative geodata (points)",
    resolution: "100 m cell; nearest stop and 500 m density; metro-station distance",
    lastImported: "Generated with npm run data:ingest --locality <id>",
    license: "ODbL 1.0",
    classification: "derived",
    limitations: "Mapped stops only; excludes service frequency, reliability and real-time arrivals.",
    usedInScoring: true,
    refresh: "Versioned OSM ingestion",
  },
  {
    id: "dailyNeeds",
    dataset: "Daily-needs retail (supermarkets, convenience, grocers)",
    provider: "OpenStreetMap contributors",
    sourceUrl: SOURCE_URLS.osm,
    purpose: "Everyday-retail access proxy",
    dataType: "Open collaborative geodata (points)",
    resolution: "100 m cell; nearest shop and 500 m density",
    lastImported: "Generated with npm run data:ingest --locality <id>",
    license: "ODbL 1.0",
    classification: "derived",
    limitations: "Reflects mapped retail only; stock, price and hours are not represented.",
    usedInScoring: true,
    refresh: "Versioned OSM ingestion",
  },
  {
    id: "greenSpace",
    dataset: "Parks, gardens and green space",
    provider: "OpenStreetMap contributors",
    sourceUrl: SOURCE_URLS.osm,
    purpose: "Green-space access proxy",
    dataType: "Open collaborative geodata (polygons)",
    resolution: "100 m cell; nearest green edge and 400 m count",
    lastImported: "Generated with npm run data:ingest --locality <id>",
    license: "ODbL 1.0",
    classification: "derived",
    limitations: "Does not assess upkeep, public access, or facilities.",
    usedInScoring: true,
    refresh: "Versioned OSM ingestion",
  },
  {
    id: "safety-proxy",
    dataset: "Police-station proximity (safety proxy)",
    provider: "OpenStreetMap contributors",
    sourceUrl: SOURCE_URLS.osm,
    purpose: "Low-confidence proximity proxy — not a crime rate",
    dataType: "Derived from OSM police points",
    resolution: "100 m cell; nearest mapped police station",
    lastImported: "Generated with npm run data:ingest --locality <id>",
    license: "ODbL 1.0",
    classification: "derived",
    limitations: "Not a crime rate. Karnataka crime data (SCRB/NCRB) is city/district-level and is not used to score cells.",
    usedInScoring: false,
    refresh: "Versioned OSM ingestion",
  },
  {
    id: "bmtc-routes",
    dataset: "BMTC route coverage and frequency context",
    provider: "BMTC (Bengaluru Metropolitan Transport Corporation) and DULT origin-destination survey 2022-23",
    sourceUrl: "https://www.bmtcinfo.com/",
    purpose: "Transit frequency and route coverage context per locality where data is available",
    dataType: "Static offline intelligence (locality-static-intelligence.json)",
    resolution: "Locality-level; not stop-level GTFS. Individual route schedules not verified.",
    lastImported: "Packaged in locality static intelligence files (vintage 2023); HSR Layout only initially",
    license: "Government public information; BMTC attribution retained",
    classification: "official",
    limitations: "BMTC does not publish GTFS. Route counts and headways are representative estimates, not real-time. Verify current schedules at bmtcinfo.com.",
    usedInScoring: false,
    refresh: "Manual versioned update when BMTC publishes updated route maps",
  },
  {
    id: "namma-metro",
    dataset: "Namma Metro station locations and alignment",
    provider: "BMRCL (Bangalore Metro Rail Corporation Limited)",
    sourceUrl: "https://www.bmrcl.co.in/",
    purpose: "Metro station proximity context for transit intelligence",
    dataType: "Static offline intelligence (locality-static-intelligence.json)",
    resolution: "Station-level; operational status subject to phase completion schedule",
    lastImported: "Packaged in locality static intelligence files (vintage 2024)",
    license: "Government public information",
    classification: "official",
    limitations: "Phase 2B completion is phased. Verify current operational status with BMRCL before display.",
    usedInScoring: false,
    refresh: "Manual update when new metro stations open",
  },
  {
    id: "osrm-routing",
    dataset: "OpenStreetMap car routing — commute time estimates",
    provider: "OSRM (Open Source Routing Machine) on OpenStreetMap data",
    sourceUrl: "https://project-osrm.org/",
    purpose: "Off-peak drive-time estimates from locality cells to key destinations",
    dataType: "Derived from OSM road network routing",
    resolution: "Cell centroid to named destination centroid; driving profile; no real-time traffic",
    lastImported: "Fetched at request time (24-hour server cache)",
    license: "ODbL 1.0 (OSM underlying data)",
    classification: "derived",
    limitations: "No traffic data. Bengaluru peak-hour times are typically 2–5× longer. Not a substitute for real-time navigation.",
    usedInScoring: false,
    refresh: "24-hour server cache; road network updates when OSM data changes",
  },
  {
    id: "bwssb-water",
    dataset: "BWSSB water supply zone and reliability context",
    provider: "Bengaluru Water Supply and Sewerage Board (BWSSB) / Jal Jeevan Mission Karnataka",
    sourceUrl: "https://bwssb.gov.in/",
    purpose: "Water supply reliability context per locality where data is available",
    dataType: "Static offline intelligence (locality-static-intelligence.json)",
    resolution: "Ward-level aggregate — individual street and building supply varies",
    lastImported: "Packaged in locality static intelligence files (vintage 2023); HSR Layout only initially",
    license: "Government public information",
    classification: "official",
    limitations: "BWSSB does not publish a real-time supply API. Data from published annual reports. Individual supply depends on pipeline zone, tanker availability, and ground-level storage.",
    usedInScoring: false,
    refresh: "Manual update from BWSSB annual reports",
  },
  {
    id: "sentinel2-ndvi",
    dataset: "Sentinel-2 NDVI — normalized difference vegetation index",
    provider: "Copernicus Data Space Ecosystem (ESA/European Commission)",
    sourceUrl: "https://dataspace.copernicus.eu/",
    purpose: "Satellite-derived green cover and vegetation density context per locality",
    dataType: "Static offline intelligence (locality-static-intelligence.json) — Sentinel-2 MSI Level-2A",
    resolution: "10 m per pixel; locality polygon aggregate (not per 100 m cell)",
    lastImported: "Packaged in locality static intelligence files (vintage 2024-07); HSR Layout only initially",
    license: "Copernicus open data — free access; ESA attribution required",
    classification: "open-data",
    limitations: "Single-date dry-season composite. Seasonal NDVI varies ±0.08 between monsoon peak and dry season. Cloud masking applied; residual artifacts possible.",
    usedInScoring: false,
    refresh: "Annual update recommended (dry season and monsoon peak comparison)",
  },
  {
    id: "landsat-lst",
    dataset: "Landsat 8 Land Surface Temperature — urban heat island analysis",
    provider: "USGS / NASA (Landsat Earth Explorer)",
    sourceUrl: "https://earthexplorer.usgs.gov/",
    purpose: "Urban heat island intensity context per locality",
    dataType: "Static offline intelligence (locality-static-intelligence.json) — Landsat 8 Band 10 thermal",
    resolution: "30 m thermal band; locality-level aggregate",
    lastImported: "Packaged in locality static intelligence files (vintage 2024-05); HSR Layout only initially",
    license: "Public domain (USGS/NASA)",
    classification: "open-data",
    limitations: "Surface temperature ≠ air temperature. May 2024 (pre-monsoon) image captures peak summer conditions. Seasonal variation is significant.",
    usedInScoring: false,
    refresh: "Annual update; dry season (March–May) for peak UHI, monsoon for comparison",
  },
  {
    id: "bbmp-sahaaya",
    dataset: "BBMP Sahaaya grievance portal — ward complaint patterns",
    provider: "BBMP (Bruhat Bengaluru Mahanagara Palike) / iChangeMyCity / Citizen Matters",
    sourceUrl: "https://bbmpsahaaya.karnataka.gov.in/",
    purpose: "Ward-level civic complaint frequency and category context per locality",
    dataType: "Static offline intelligence (locality-static-intelligence.json) — aggregated from public portals",
    resolution: "Ward-level aggregate; not cell-level or street-level",
    lastImported: "Packaged in locality static intelligence files (vintage 2022-23); HSR Layout only initially",
    license: "Public grievance data; attribution retained",
    classification: "open-data",
    limitations: "Complaint counts reflect registered grievances only; under-reporting is significant. Not a comprehensive audit of civic conditions.",
    usedInScoring: false,
    refresh: "Annual update from BBMP Sahaaya and iChangeMyCity ward data",
  },
  {
    id: "ncrb-crime",
    dataset: "NCRB Crime in India 2022 — Bengaluru City district-level statistics",
    provider: "National Crime Records Bureau (NCRB), Ministry of Home Affairs, Government of India",
    sourceUrl: "https://ncrb.gov.in/",
    purpose: "City-level crime context; explicitly NOT used for locality scoring due to resolution",
    dataType: "Static offline intelligence — NCRB published annual report",
    resolution: "Bengaluru City district aggregate; ward/locality breakdown is not publicly available",
    lastImported: "Packaged in locality static intelligence files (vintage 2022)",
    license: "Government public data",
    classification: "official",
    limitations: "No ward or locality level data is available. Using city-level data for neighbourhood scoring would be misleading. Shown as context only with explicit limitation note.",
    usedInScoring: false,
    refresh: "Annual NCRB report (typically published 12-18 months after reference year)",
  },
  {
    id: "trai-internet",
    dataset: "TRAI Broadband Report and ISP coverage context for Bengaluru",
    provider: "Telecom Regulatory Authority of India (TRAI) and public ISP coverage maps",
    sourceUrl: "https://www.trai.gov.in/",
    purpose: "Internet connectivity and fiber availability context per locality",
    dataType: "Static offline intelligence (locality-static-intelligence.json)",
    resolution: "Karnataka telecom circle aggregate + known ISP presence per locality where available",
    lastImported: "Packaged in locality static intelligence files (vintage 2023-24); HSR Layout only initially",
    license: "Government public data; Ookla cited for research only",
    classification: "official",
    limitations: "TRAI data is circle-level, not locality-level. ISP coverage maps are indicative; actual building-level availability depends on last-mile infrastructure.",
    usedInScoring: false,
    refresh: "Annual update from TRAI quarterly broadband report",
  },
];
